#!/usr/bin/env bash

# this file sets the following system-wide variables for the VM

# setting an array of environmental variables
declare -a ENV_VARIABLES=(
	"HOME_DIR=/home/vagrant"
	"SHARED_DIR=/vagrant"
	"DOWNLOAD_DIR=/downloads"
	"DJATOKA_HOME=/usr/local/djatoka"
	"FEDORA_HOME=/usr/local/fedora"
	"FFMPEG_VERSION=1.1.4"
	"FITS_HOME=/usr/local/fits"
	"FITS_VERSION=0.10.1"
	"SOLR_HOME=4.2.0"
	"SOLR_VERSION=/usr/local/solr"
	"DRUPAL_HOME=/var/www/drupal"
)

check_etc_environment() {
	echo "Checking /etc/environment values"
	for i in "${ENV_VARIABLES[@]}"
	do
		if grep -F -x -q "$i" /etc/environment; then
			echo "$i is okay"
		else
			echo "$i is missing"
			echo "$i" >> /etc/environment
		fi
	done
	echo "(re)sourcing /etc/environment"
	sudo su -c "source /etc/environment"
}

echo "cat-ing /etc/environment"
#check_etc_environment
cat /etc/environment
echo "all done"