#!/bin/bash

# this file sets the following system-wide variables for the VM

echo "setting HOME_DIR"
echo HOME_DIR="/home/vagrant" >> /etc/environment

# Shared comes from shell provisioner in VagrantFile
echo "setting DOWNLOAD_DIR"
echo DOWNLOAD_DIR="$SHARED_DIR/downloads" >> /etc/environment

echo "setting DJATOKA_HOME"
echo DJATOKA_HOME="/usr/local/djatoka" >> /etc/environment

echo "setting FEDORA_HOME"
echo FEDORA_HOME="/usr/local/fedora" >> /etc/environment

echo "setting FFMPEG_VERSION"
echo FFMPEG_VERSION=1.1.4 >> /etc/environment

echo "setting FITS_HOME and FITS_VERSION"
echo FITS_HOME="/usr/local/fits" >> /etc/environment
echo FITS_VERSION=0.10.1 >> /etc/environment

echo "setting SOLR_HOME and SOLR_VERSION"
echo SOLR_HOME="/usr/local/solr" >> /etc/environment
echo SOLR_VERSION=4.2.0 >> /etc/environment

echo "setting DRUPAL_HOME"
echo DRUPAL_HOME="/var/www/drupal" >> /etc/environment

source /etc/environment
